# Generated by Django 4.1.7 on 2023-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(default="hobby", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="time",
            field=models.DateTimeField(auto_now_add=True, default="2023-03-31 12:00"),
            preserve_default=False,
        ),
    ]
